# Configuration for solana-validator-ha binary to use with mock server
validator:
  name: validator-3
  rpc_url: http://localhost:8989/validator-3-rpc
  public_ip_service_urls:
    - http://localhost:8989/validator-3/public-ip
  identities:
    active: active-identity.json
    passive: passive-identity.json

cluster:
  name: mainnet-beta
  rpc_urls:
    - http://localhost:8989/solana-network-rpc
prometheus:
  port: 9099

failover:
  active:
    command: ../set-identity.sh
    args: ["3", active]
  passive:
    command: ../set-identity.sh
    args: ["3", passive]
  peers:
    validator-1:
      ip: 192.168.1.101
    validator-2:
      ip: 192.168.1.102
