# Configuration for solana-validator-ha binary to use with mock server
validator:
  name: validator-1
  rpc_url: http://localhost:8989/validator-1-rpc
  public_ip_service_urls:
    - http://localhost:8989/validator-1/public-ip
  identities:
    active: active-identity.json
    passive: passive-identity.json

cluster:
  name: mainnet-beta
  rpc_urls:
    - http://localhost:8989/solana-network-rpc

prometheus:
  port: 9091

failover:
  active:
    command: ../set-identity.sh
    args: ["1", active]
  passive:
    command: ./restart-validator-as.sh
    args: [passive]
  peers:
    validator-2:
      ip: 192.168.1.102
    validator-3:
      ip: 192.168.1.103
